---
title: "Evidensbaserade insatser och bästa tillgängliga kunskap"
title-block-banner: "#009ca6"
title-block-banner-color: "#f0f0f0"
---

## Evidensbaserade insatser och bästa tillgängliga kunskap
Här finner du en samling av information kring evidensbaserade insatser kopplat till de åtta folkhälsopolitiska målområdena.

### Tidiga livets villkor

Det finns flera myndigheter och organisationer som tillhandahåller information kring evidensbaserade insatser kopplade till det tidiga livets villkor. Nedan finner du ingångar till dessa.

**Evidensbaserade insatser**

*Mydigheten för familjerätt och föräldraskapsstöd*

- [En nationell översikt av program och metoder för föräldraskapsstöd](https://mfof.se/foraldraskapsstod/program-och-metoder.html)

*SBU*

- [Metoder och insatser inom socialtjänsten för barn och unga](https://www.sbu.se/sv/publikationer/tema-socialstjanst-ny/barn-och-unga/)

*Socialstyrelsen*

- [Kunskapsguiden: Insatser till barn med hög risk för fortsatt normbrytande beteende](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/barn-och-unga-som-begar-brott/rekommendationer-om-insatser-till-barn-med-hog-risk-for-fortsatt-normbrytande-beteende/)

- [Kunskapsguiden: Tidiga och samordnade insatser (TSI)](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/)


*Föreningen för familjecentralers främjande*

- [Vad är en familjecentral?](https://familjecentraler.se/foreningen/vad-ar-en-familjecentral/)


**Ej utvärderade insatser**

- [Early Identification System - Ett skolbaserat verktyg för att tidigt kunna identifiera individer med behov av stöd, anpassning eller insats](https://www.ri.se/sv/vad-vi-gor/projekt/early-identification-system)

**Lokala exempel**

XX

**Indikatorer**

XX

**Läs mer**

XX

### Kunskaper, kompetenser och utbildning

### Arbete, arbetsförhållanden och arbetsmiljö

### Inkomster och försörjningsmöjligheter

### Boende och närmiljö

### Levnadsvanor

### Kontroll inflytande och delaktighet

### Jämlik hälsofrämjande hälso och sjukvård











