name: Publish Quarto Book

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.553'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev pandoc

      - name: Render book
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
